* notmuch-notify

Notification for notmuch upon new email arrival.

*Features*:
- Notification and sound effect upon new email arrival.
- Message about the change of the number of messages whenever =notmuch-hello= is
  refreshed.

** Installation & Configuration
The following configuration relies on [[https://github.com/quelpa/quelpa-use-package][quelpa-use-package]], but it is
straightforward to clone this repo locally and use =use-package= instead.
Moreover, this package uses =alert= as notification backend. See [[https://github.com/jwiegley/alert][jwiegley/alert]]
for options to fine-tune notifications (/e.g./ =alert-default-style=).

#+begin_src emacs-lisp
(use-package notmuch-notify
  :ensure t
  :quelpa (notmuch-notify :fetcher github :repo "firmart/notmuch-notify")
  ;; (Recommended) activate stats message when refreshing notmuch-hello buffer
  :hook (notmuch-hello-refresh . notmuch-notify-hello-refresh-status-message)
  :config
  ;; (Recommended) activate system-wise notification timer
  (notmuch-notify-set-refresh-timer)
  ;; Default configurations
  (setq notmuch-notify-alert-severity 'normal ;; 'trivial, 'low, 'normal, 'moderate, 'high, 'urgent
	notmuch-notify-alert-title "Notmuch: new message"
	;; absolute path for alert icon & audio file
	notmuch-notify-alert-icon (expand-file-name "notmuch-logo.png" ".")
	notmuch-notify-alert-audio-file (expand-file-name "emailreceived.wav" ".")
	notmuch-notify-alert-audio-program "mpv"
	notmuch-notify-excluded-tags nil ;; list of tag(s) that will not trigger alert
	notmuch-notify-refresh-interval 60) ;; refresh interval in seconds
  )
#+end_src

** Todo
- Allow different severity/logo/sound for different tag/address/content.
- Display new email title in the alert.

** Contribution
Issues and PRs are welcomed.

** Acknowledgement
- [[https://notmuchmail.org/emacstips/#index19h2][Notmuch: Emacs tips]] for the status refresh function.
- System notification inspired from [[https://github.com/wlemuel/alarm-clock][wlemuel/alarm-clock]].
- Default sound effect (=receivedemail.wav=) comes from [[https://freesound.org/people/Jrcard/sounds/421924/][Freesound]] (CC0).
